### ISSUE TITLE
`global is not defined` when using with vite

### ISSUE THREAD

**Issue by noway** [strangelove-ventures/wadesta#13]
## Describe the bug

Package throws the following error when trying to import on a vite react project:

```
_stream_readable.js:48 Uncaught ReferenceError: global is not defined
    at node_modules/readable-stream/lib/_stream_readable.js (_stream_readable.js:48:21)
    at __require2 (chunk-Q7D65HC4.js?v=6a1b80ec:18:50)
    at node_modules/readable-stream/readable-browser.js (readable-browser.js:1:28)
    at __require2 (chunk-Q7D65HC4.js?v=6a1b80ec:18:50)
    at node_modules/hash-base/index.js (index.js:3:17)
    at __require2 (chunk-Q7D65HC4.js?v=6a1b80ec:18:50)
    at node_modules/md5.js/index.js (index.js:3:16)
    at __require2 (chunk-Q7D65HC4.js?v=6a1b80ec:18:50)
    at node_modules/create-hash/browser.js (browser.js:3:11)
    at __require2 (chunk-Q7D65HC4.js?v=6a1b80ec:18:50)
node_modules/readable-stream/lib/_stream_readable.js @ _stream_readable.js:48
__require2 @ chunk-Q7D65HC4.js?v=6a1b80ec:18
node_modules/readable-stream/readable-browser.js @ readable-browser.js:1
__require2 @ chunk-Q7D65HC4.js?v=6a1b80ec:18
node_modules/hash-base/index.js @ index.js:3
__require2 @ chunk-Q7D65HC4.js?v=6a1b80ec:18
node_modules/md5.js/index.js @ index.js:3
__require2 @ chunk-Q7D65HC4.js?v=6a1b80ec:18
node_modules/create-hash/browser.js @ browser.js:3
__require2 @ chunk-Q7D65HC4.js?v=6a1b80ec:18
node_modules/bip39/src/index.js @ index.js:3
__require2 @ chunk-Q7D65HC4.js?v=6a1b80ec:18
node_modules/@cosmjs/launchpad/node_modules/@cosmjs/crypto/build/bip39.js @ bip39.ts:2
__require2 @ chunk-Q7D65HC4.js?v=6a1b80ec:18
node_modules/@cosmjs/launchpad/node_modules/@cosmjs/crypto/build/index.js @ index.ts:1
__require2 @ chunk-Q7D65HC4.js?v=6a1b80ec:18
node_modules/@cosmjs/launchpad/build/address.js @ address.ts:1
__require2 @ chunk-Q7D65HC4.js?v=6a1b80ec:18
node_modules/@cosmjs/launchpad/build/index.js @ index.ts:4
__require2 @ chunk-Q7D65HC4.js?v=6a1b80ec:18
node_modules/@keplr-wallet/cosmos/build/adr-36/amino.js @ amino.ts:1
__require2 @ chunk-Q7D65HC4.js?v=6a1b80ec:18
node_modules/@keplr-wallet/cosmos/build/adr-36/index.js @ index.ts:1
__require2 @ chunk-Q7D65HC4.js?v=6a1b80ec:18
node_modules/@keplr-wallet/cosmos/build/stargate/wrapper/index.js @ index.ts:4
__require2 @ chunk-Q7D65HC4.js?v=6a1b80ec:18
node_modules/@keplr-wallet/cosmos/build/stargate/index.js @ index.ts:3
__require2 @ chunk-Q7D65HC4.js?v=6a1b80ec:18
node_modules/@keplr-wallet/cosmos/build/index.js @ index.ts:5
__require2 @ chunk-Q7D65HC4.js?v=6a1b80ec:18
(anonymous) @ index.mjs:1
```

## To Reproduce

1. Create a vite app with react typescript template
2. yarn add graz
3. Try to import

## Expected behavior

No error

## Screenshots

<img width="474" alt="image" src="https://user-images.githubusercontent.com/2031472/178960464-d3447ca6-1df5-45a2-a144-c13c1b22e2b5.png">

## Device

> Please complete the following device information.

**Desktop**

- OS: MacOS
- Browser Chrome
- Version 103

## Additional context

Vite might not have a polyfier/babel transfomer for `global`.

**Comment by grikomsn** [comment]
Apparently this is not a `graz` specific issue but more on Vite's end where it [does not polyfill Node.js built-in globals and modules](https://duckduckgo.com/?q=vite+node+polyfill&ia=web).

The solution is to polyfill required modules that `graz` and its internals using [`vite-plugin-ngmi-polyfill`](https://github.com/grikomsn/vite-plugin-ngmi-polyfill)[^1]. Here's an example app using Vite + React + TypeScript to learn more:

- https://github.com/strangelove-ventures/graz-vite-example
- https://graz-vite-example.vercel.app

[^1]: I made this plugin while investigating this issue. Also this is the first time I tried Vite.
